name: Build EXE on Tag

on:
  push:
    tags:
      - 'v*'   # dispara quando uma tag "vX.X.X" é criada (ex: v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile batch_audio_to_text_whisper.py
          dir dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: audio-to-text-exe
          path: dist/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: audio-to-text-exe
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
